config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments, only: [:create, :destroy]
    get :test_2, on: :member
  end

  resources :contacts, only: [:create, :index, :new, :destroy]


  root 'pages#home'

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user
    guest_abilities
    user_abilities if @user.present?
    admin_abilities if @user.present? && @user.admin?
  end

  def guest_abilities
    can :read, Article
    cannot :create, Article
    cannot :destroy, Comment
    cannot :create, Comment
    cannot :manage, Message
  end

  def user_abilities
    can :update, Article, user: @user
    can :destroy, Article, user: @user
    can :create, Article
    can :create, Comment
    cannot :destroy, Comment
    cannot :read, Message
    can :create, Message
    cannot :destroy, Message
  end

  def admin_abilities
    can :manage, :all
  end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :delete_all

  validates :title, presence: true, length: { minimum: 1, maximum: 50 }

  validates :description, presence: true, length: { minimum: 1, maximum: 150 }
  
  validates :user_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
    validates :text, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence: true,
  format: { with: VALID_EMAIL_REGEX }

  validates :title, presence: true,
  length: { minimum: 5, maximum: 50}

  validates :description, length: { maximum: 500 }


end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles

  has_many :messages

  before_save { self.email = email.downcase }

  validates :username, presence: true,
  uniqueness: { case_sensitive: false },
  length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
  uniqueness: { case_sensitive: false }, length: { maximum: 105 },
  format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

  def logged_in?
    !!current_user
  end

  rescue_from CanCan::AccessDenied do |exception|
      respond_to do |format|
        format.json { head :forbidden }
        format.html { redirect_to articles_path, :alert => exception.message }
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  def index; end

  def new; end

  def edit; end

  def test_2; end

  def update
    if @article.update(article_params)
      flash[:notice] = "Artykuł zaaktualizowany"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def create
   @article = Article.new(article_params)
   @article.user = current_user
   if @article.save
     flash[:success] = "Artykuł utworzono pomyślnie"
     redirect_to article_path(@article)
   else
     render 'new'
   end
  end

  def show
    @comments = @article.comments
    @comment = Comment.new
  end

  def destroy
    if  @article.destroy
      flash[:notice] = "Usunięto artykuł"
      redirect_to articles_path
    else
      render 'index'
      flash[:notice] = "Wystąpił błąd"
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource :article
  load_and_authorize_resource :comment, through: :article

  def new; end


    def create
      @comment = @article.comments.new(comment_params)
      if @comment.save
        flash[:success] = "Pomyślnie utworzono komentarz"
        redirect_to article_path(@article)
      else
        flash[:notice] = "Wystąpił błąd"
      end
    end


    def destroy
      @comment = @article.comments.find(params[:id])
      if @comment.destroy
        flash[:notice] = "Pomyślnie usunięto komentarz"
        redirect_to article_path(@comment.article)
      else
        render 'show'
        flash[:notice] = "Wystąpił błąd"
      end
    end

    private

      def comment_params
        params.require(:comment).permit(:text)
      end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
load_and_authorize_resource class: "Message", param_method: :message_params

  def index
    @messages = @contacts
  end

  def new
    @message = @contact
  end

  def create
    @message = @contact
     if @message.save
       flash[:success] = "Wiadomość stworzona"
       redirect_to new_contact_path
       UserMailer.smail(@message).deliver_now
     else
       render 'new'
    end
  end

  def destroy
    @message = @contact
    if @message.destroy
      flash[:notice] = "Usunięto wiadomość"
      redirect_to contacts_path
    else
      render 'index'
      flash[:notice] = "Wystąpił błąd"
    end
  end

  private
  def message_params
    params.require(:message).permit(:title, :email, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Zalogowano pomyślnie"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Email albo hasło nieprawidłowe"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Wylogowano"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:edit, :update, :show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Witaj, #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = "Zaaktualizowano konto"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show; end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_article.haml
- obj.each do |article|
  .center
    .row
      .col-xs-8.col-xs-offset-2
        .well.well-lg
          .article-title
            = link_to article.title, article_path(article)
          .article-body
            = truncate(article.description, length: 100)
            .article-meta-details
              %small
                Utworzony przez: #{article.user.username if article.user},
                \#{time_ago_in_words(article.created_at)} temu,
                last updated: #{time_ago_in_words(article.updated_at)}
                temu
          - if can? :manage, Article, user: @user
            .article-actions
              = link_to "Edytuj ten artykuł",   |
                edit_article_path(article),     |
                class: "btn btn-xs btn-primary" |
              -#
              = link_to "Usuń ten artykuł",                                   |
                article_path(article),                                        |
                method: :delete,                                              |
                data: { confirm: "Czy na pewno chcesz usunąć ten artykuł?" }, |
                class: "btn btn-xs btn-danger"                                |

app/views/articles/_cform.haml
.comment
  = form_for [@article, @comment] do |f|
    %p
      = f.label :text
      %br/
      = f.text_area :text
    %p
      = f.submit

app/views/articles/_form.haml
= render 'shared/errors', obj: @article
.row
  .col-xs-12
    = form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f|
      .form-group
        .control-label.col-sm-2
          = f.label :Tytuł
        .col-sm-8
          = f.text_field :title,
            class: "form-control",         
            placeholder: "Tytuł artykułu",
            autofocus: true
      .form-group
        .control-label.col-sm-2
          = f.label :Treść
        .col-sm-8
          = f.text_area :description, rows: 9, class: "form-control", placeholder: "Wpisz treść artykułu"
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.submit class: 'btn btn-primary btn-lg'
    .col-xs-4.col-xs-offset-4
      = link_to 'Lista', articles_path

app/views/articles/_index.haml
%h1 Comments
- @comments.each do |comment|
  .row
    .col-xs-8.col-xs
      .well.well-lg
        .article-body
          = truncate(comment.text, length: 100)
        .article-actions
          = link_to "Usuń ten komentarz",                                   |
            article_comment_path(@article, comment),                        |
            method: :delete,                                                |
            data: { confirm: "Czy na pewno chcesz usunąć ten komentarz?" }, |
            class: "btn btn-xs btn-danger"                                  |

app/views/articles/cnew.haml
%h1 Dodaj komentarz
= render 'cform'

app/views/articles/edit.haml
%h1.center Edytuj artykuł
= render 'form'

app/views/articles/index.haml
%h1{:align => "center"} Lista
- if can? :destroy, @article
  = link_to "Stwórz nowy artykuł", new_article_path(@article)
= render 'article', obj: @articles

app/views/articles/new.haml
%h1.center Stwórz artyuł

= render 'form' 

app/views/articles/show.haml
%h1{:align => "center"}
  Tytuł: #{@article.title}
.well.col-xs-8.col-xs-offset-2
  - if @article.user
    %ul.listing
      .row.center
        .col-md-4.col-md-offset-4
          %li Utworzony przez:
          %li= link_to gravatar_for(@article.user), user_path(@article.user)
          %li.article-title
            = link_to @article.user.username, user_path(@article.user)
          %li
            %small= pluralize(@article.user.articles.count, "article") if @article.user.articles
  %h4.center.description Treść
  = render 'cform'
  = render 'index'

app/views/articles/test_2.haml
%h1{:align => "center"}
  Title: #{@article.title}
.well.col-xs-8.col-xs-offset-2
  - if @article.user
    %ul.listing
      .row.center
        .col-md-4.col-md-offset-4
          %li Created by:
          %li= link_to gravatar_for(@article.user), user_path(@article.user)
          %li.article-title
            = link_to @article.user.username, user_path(@article.user)
          %li
            %small= pluralize(@article.user.articles.count, "article") if @article.user.articles
  %h4.center.description
    %strong Description

app/views/comments/_cform.haml
= form_for @comment do |f|
  %p
    = f.label :text
    %br/
    = f.text_area :text
  %p
    = f.submit
= link_to 'Lista', articles_path

app/views/comments/new.haml
%h1 Dodaj komentarz
= render 'cform' 

app/views/contacts/index.haml
%table
  - @messages.each do |message|
    .center
      .row
        .col-xs-8.col-xs-offset-2
          .well.well-lg
            .article-title
              = message.title
              %br/
              %small
                sent to:
                = message.email
            .article-body
              = truncate(message.description, length: 500)
            - if can? :manage, Message, user: @user
              .article-actions
                = link_to "Usuń tę wiadomość", contact_path(message), method: :delete, data: { confirm: "Czy na pewno chcesz usunąć tę wiadomość?" }, class: "btn btn-xs btn-danger"

app/views/contacts/new.haml
= render 'messages/new' 

app/views/layouts/_footer.haml
.container
  %footer.footer
    %small
      Copyright ©
      %a{:href => "https://www.google.pl/"} costam
      by albert

app/views/layouts/_messages.haml
.row
  .col-xs-10.col-xs-offset-1
    - flash.each do |name, msg|
      %div{:class => "alert alert-#{"#{name}"}"}
        %a.close{"data-dismiss" => "alert", :href => "#"} ×
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "BLOG", root_path, class: "navbar-brand", id: "logo"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "Artykuły", articles_path
        - if can? :manage, :all
          %li= link_to "Użytkownicy", users_path
        - if can? :create, Article
          %li= link_to "Stwórz nowy artykuł", new_article_path
      %form.navbar-form.navbar-left
        .form-group
          %input.form-control{:placeholder => "Szukaj...", :type => "text"}/
        %button.btn.btn-default{:type => "submit"} Znajdź
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            - if logged_in?
              = current_user.email
              %span.caret
          %ul.dropdown-menu
            %li= link_to 'Stwórz nową wiadomość', new_contact_path(@message)
            %li.divider{:role => "separator"}
            - if can? :read, Message
              %li= link_to 'Pokaż wszystkie wiadomości', contacts_path
        - if logged_in?
          %li= link_to 'Wyloguj się', logout_path, method: :delete
        - else
          %li= link_to 'Zaloguj się', login_path
        %li= link_to 'Zarejestruj się', signup_path
    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/application.haml
!!!
%html
  %head
    %title Dziala
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    .container
      = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?

app/views/messages/_new.haml
%a.envelope-icon{:href => "email@gmail.com"}
%h2.new-msg-h2 Contact us
= render 'shared/errors', obj: @message
.row
  .col-xs-12
    = form_for(@message, url: contacts_path, :html => {class: "form-horizontal", role: "form"}) do |f|
      .form-group
        .control-label.col-sm-2
          = f.label :Tytuł
        .col-sm-8
          = f.text_field :title,
            class: "form-control",
            placeholder: "Wprowadź tytuł",
            autofocus: true
      .form-group
        .control-label.col-sm-2
          = f.label :email
        .col-sm-8
          = f.email_field :email,
            class: "form-control",
            placeholder: "Wprowadź email",
            autofocus: true
      .form-group
        .control-label.col-sm-2
          = f.label :Treść
        .col-sm-8
          = f.text_area :description, rows: 9, class: "form-control", placeholder: "Wprowadź treść"
      .form-group
        .col-sm-offset-5.col-sm-1
          = f.submit 'Wyślij', rows: 9, class: 'btn btn-primary btn-lg'
    .col-xs-4.col-xs-offset-4
      = link_to 'Lista', articles_path

app/views/pages/home.haml
.center.jumbotron
  %h1 BLOG
  = link_to "Zarejestruj się", signup_path, class: "btn btn-danger btn-lg btn-xlarge"

app/views/shared/_errors.haml
- if obj.errors.any?
  .row
    .col-xs-8.col-xs-offset-2
      .panel.panel-danger
        .panel-heading
          %h2.panel-title
            = pluralize(obj.errors.count, "error")
            prohibited this article from being save:
          .panel-body
            %ul
              - obj.errors.full_messages.each do |msg|
                %li= msg

app/views/users/_form.haml
.row
  .col-xs-12
    = form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f|
      .form-group
        .control-label.col-sm-2
          = f.label :Nazwa_użytkownika
        .col-sm-8
          = f.text_field :username,                    |
            class: "form-control",                     |
            placeholder: "Wprowadź nazwę użytkownika", |
            autofocus: true                            |
      .form-group
        .control-label.col-sm-2
          = f.label :Hasło
        .col-sm-8
          = f.password_field :password,
            class: "form-control",
            placeholder: "Wprowadź hasło" 
      .form-group
        .control-label.col-sm-2
          = f.label :email
        .col-sm-8
          = f.email_field :email,
            class: "form-control",
            placeholder: "Wprowadź email"
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.submit(@user.new_record? ? "Zarejestruj się" : "Zaaktualizuj konto", class: 'btn btn-primary btn-lg')
    .col-xs-4.col-xs-offset-4
      = link_to 'Lista', articles_path

app/views/users/edit.haml
%h1{:align => "center"} Edit your account
= render 'form'

app/views/users/index.haml
%h1{:align => "center"} Lista użytkowników
%div{:align => "center"}
  - @users.each do |user|
    %ul.listing
      .row
        .well.col-md-4.col-md-offset-4
          %li= link_to gravatar_for(user), user_path(user)
          %li.article-title
            = link_to user.username, user_path(user)
          %li
            %small= pluralize(user.articles.count, "article") if user.articles

app/views/users/new.haml
%h1{:align => "center"} Create an account
= render 'form'

app/views/users/show.haml
%h1{:align => "center"}= @user.username
.rows
  .col-md-4.col-md-offset-4.center
    = gravatar_for @user, size:150
%br/
%h4.user-articles
  = @user.username
  's articles
= render 'articles/article', obj: @user.articles